#!/usr/bin/env bash

DB_HOST=aserto-ds-prod.cn68oku6wf3q.us-east-2.rds.amazonaws.com
DB_USER=postgres

pg_dump -h ${DB_HOST} -U ${DB_USER} ds > ds.sql
psql -A -t -h ${DB_HOST} -U ${DB_USER} ds -c "SELECT schema_name FROM information_schema.schemata WHERE schema_name LIKE '%-%-%-%-%';" > ds-roles.sql


